repos:
    -   repo: https://github.com/python-poetry/poetry
        rev: "1.8"
        hooks:
        -   id: poetry-lock
        -   id: poetry-export
            args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]
