[project]
name = "metavoice"
version = "0.1.0"
description = "Foundational model for text to speech"
requires-python = ">=3.10,<3.12"

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
