name: Sync Fork

on:
  schedule:
    - cron:  '0 0 */7 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'

    - name: Add Upstream
      run: git remote add upstream https://github.com/metavoiceio/metavoice-src.git

    - name: Fetch Upstream
      run: git fetch upstream

    - name: Checkout Main Branch
      run: git checkout main

    - name: Merge Upstream
      run: git merge upstream/main

    - name: Push Changes
      run: git push origin main
